// <auto-generated />

// Copyright (c) Six Labors and contributors.
// See LICENSE for more details.

#if SUPPORTS_SERIALIZATION
using System.Runtime.CompilerServices;

[assembly: TypeForwardedTo(typeof(System.SerializableAttribute))]
#else
namespace System
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Delegate, Inherited = false)]
    public sealed class SerializableAttribute : Attribute
    {
        public SerializableAttribute() { }
    }
}
#endif
