// <auto-generated />

// Copyright (c) 2018-2020, Els_kom org.
// https://github.com/Elskom/
// All rights reserved.
// license: See LICENSE for more details.

#if SUPPORTS_SERIALIZATION
using System.Runtime.CompilerServices;

[assembly: TypeForwardedTo(typeof(System.SerializableAttribute))]
#else
namespace System
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Delegate, Inherited = false)]
    public sealed class SerializableAttribute : Attribute
    {
        public SerializableAttribute() { }
    }
}
#endif
